# Dependabot version updates.
# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    groups:
      ruby-minor-patch:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types:
          - 'minor'
          - 'patch'
