AllCops:
  NewCops: disable
  Exclude:
    - 'db/schema.rb'
require: rubocop-rails

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'
