FROM ruby:3.3.4-slim

ENV APP_PATH=/var/app
ENV BUNDLE_VERSION=2.5.21
ENV BUNDLE_PATH=/usr/local/bundle/gems
ENV RAILS_LOG_TO_STDOUT=true
ENV RAILS_PORT=3000
ENV RAILS_ENV=development
ENV BUNDLE_FORCE_RUBY_PLATFORM=1
ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1

# Install dependencies for application
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    git \
    libpq-dev \
    postgresql-client \
    libxml2 \
    libxml2-dev \
    libxslt1-dev \
    nodejs \
    npm \
    imagemagick \
    tzdata \
    less \
    libyaml-dev \
    pkg-config \
    && npm install -g yarn \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p $APP_PATH

# Update gem system and install bundler
RUN gem update --system 3.6.2 \
    && gem install bundler --version "$BUNDLE_VERSION" \
    && rm -rf $GEM_HOME/cache/*

WORKDIR $APP_PATH

COPY ../Gemfile ../Gemfile.lock ../.ruby-version ../vendor ./

# Install all gems into the image
RUN bundle config set --local path 'vendor/bundle' \
    && bundle install --jobs 1 --retry 3 \
    && rm -rf vendor/bundle/ruby/3.3.0/cache/*.gem

# Copy the rest of the application
COPY ../. ./

# Copy entrypoint scripts and grant execution permissions
COPY ./docker/web-entrypoint.sh /usr/local/bin/web-entrypoint.sh
RUN chmod +x /usr/local/bin/web-entrypoint.sh

COPY ./docker/sidekiq-entrypoint.sh /usr/local/bin/sidekiq-entrypoint.sh
RUN chmod +x /usr/local/bin/sidekiq-entrypoint.sh

EXPOSE $RAILS_PORT

ENTRYPOINT [ "bundle", "exec" ]
