defmodule Dawarich.RailsJobOwners do
  @moduledoc false

  alias Dawarich.ReleaseOperations.PlacesUserId

  @slices ~w(a4 a7 a8 a9 a12c a12d1 a12d2 a12h)a
  @mail ~w(command:users.explore_features_mail command:mail.user.welcome command:mail.user.archival_approaching command:mail.user.oauth_account_link command:mail.user.account_destroy_confirmation)

  @owners %{
    "Achievements::BulkCheckJob" => {:slice, :a12d2},
    "Achievements::CheckJob" => {:oban, ["command:achievements.check"]},
    "AirTrail::ImportFlightsJob" => {:oban, ["command:imports.airtrail_flights"]},
    "AirTrail::SyncSchedulingJob" => {:slice, :a12d2},
    "AppVersionCheckingJob" => {:oban, ["cron:app_version_checking_job"]},
    "Areas::RelabelVisitsJob" => {:oban, ["command:areas.relabel_visits"]},
    "BulkStatsCalculatingJob" => {:slice, :a12d1},
    "BulkVisitsSuggestingJob" => {:slice, :a12d2},
    "Cache::CleaningJob" => {:slice, :a12d1},
    "Cache::PreheatingJob" => {:slice, :a12d1},
    "Cache::UserPreheatingJob" => {:slice, :a12d1},
    "DataMigrations::AddPointDimensionColumnsJob" => {:slice, :a12h},
    "DataMigrations::BackfillAchievementsJob" => {:slice, :a12d2},
    "DataMigrations::BackfillAltitudeJob" => {:oban, ["command:release.altitude"]},
    "DataMigrations::BackfillAltitudeUserJob" => {:oban, ["command:release.altitude"]},
    "DataMigrations::BackfillCountryNameJob" => :retire,
    "DataMigrations::BackfillFamiliesForFamilyPlanJob" => :retire,
    "DataMigrations::BackfillFamilyMemberEntitlementsJob" => :retire,
    "DataMigrations::BackfillMotionDataJob" => {:oban, ["command:release.motion_data"]},
    "DataMigrations::BackfillOnboardingCompletedJob" =>
      {:oban, ["command:release.onboarding_completed"]},
    "DataMigrations::BackfillPlaceNameLocksJob" => {:oban, ["command:release.place_name_locks"]},
    "DataMigrations::BackfillPlacesUserIdJob" => {:migrator, PlacesUserId},
    "DataMigrations::BackfillPointCountryIdJob" =>
      {:oban, ["command:release.point_dimensions_country"]},
    "DataMigrations::BackfillPointDimensionsJob" =>
      {:oban, ["command:release.point_dimensions_country"]},
    "DataMigrations::BackfillTransportationModesJob" =>
      {:oban, ["command:release.transportation"]},
    "DataMigrations::CleanupNullIslandJob" => {:oban, ["command:release.null_island"]},
    "DataMigrations::DedupeTracksForUniqueIndexJob" => :retire,
    "DataMigrations::DestroyOrphanedTracksJob" => {:oban, ["command:release.orphaned_tracks"]},
    "DataMigrations::DropLegacyLatLonJob" => {:slice, :a12h},
    "DataMigrations::FixRouteOpacityJob" => {:oban, ["command:release.route_opacity"]},
    "DataMigrations::MigratePlacesLonlatJob" => :retire,
    "DataMigrations::PrefillPointsCounterCacheJob" => :retire,
    "DataMigrations::RecalculateAnomaliesJob" => {:slice, :a12d1},
    "DataMigrations::RecalculateAnomaliesUserJob" => {:slice, :a12d1},
    "DataMigrations::RecalculatePerTrackerTracksJob" => {:slice, :a12d1},
    "DataMigrations::SetPointsCountryIdsJob" => :retire,
    "DataMigrations::SetReverseGeocodedAtForPointsJob" => :retire,
    "DataMigrations::StartSettingsPointsCountryIdsJob" => :retire,
    "EnhancedImport::DestroyJob" => {:oban, ["command:enhanced_import.destroy_gpx"], :a7},
    "EnhancedImport::ExtractJob" => {:oban, ["command:enhanced_import.extract_gpx"], :a7},
    "EnqueueBackgroundJob" => {:slice, :a12d2},
    "ExportJob" => {:oban, ["command:exports.points"]},
    "Families::AutoCreationJob" => {:slice, :a12d2},
    "Families::ExpireLocationRequestsJob" =>
      {:oban, ["cron:family_location_requests_expiry_job"]},
    "Families::LapseNotificationJob" => {:oban, ["command:mail.family_lapse"]},
    "Families::MemberSyncJob" => {:slice, :a12d2},
    "Family::Invitations::CleanupJob" => {:oban, ["cron:nightly_family_invitations_cleanup_job"]},
    "Family::Invitations::SendingJob" => {:oban, ["command:mail.family_invitation"]},
    "Immich::VerifyEnrichmentJob" => {:slice, :a4},
    "Import::GoogleTakeoutJob" => {:slice, :a7},
    "Import::GpxResumeJob" => {:slice, :a7},
    "Import::ImmichGeodataJob" => {:slice, :a7},
    "Import::PhotoprismGeodataJob" => {:slice, :a7},
    "Import::ProcessJob" => {:oban, ["command:imports.process_gpx"], :a7},
    "Import::UpdatePointsCountJob" => {:oban, ["command:imports.update_points_count"]},
    "Import::WatcherJob" => {:slice, :a7},
    "Imports::DestroyJob" => {:oban, ["command:imports.destroy"], :a7},
    "Imports::PrepareDownloadJob" => {:oban, ["command:imports.prepare_download"], :a7},
    "Lite::ArchivalWarningJob" => {:oban, ["cron:lite_archival_warning_job"]},
    "Partnero::CustomerSignupJob" => {:slice, :a12d2},
    "PendingImports::CleanupJob" => {:slice, :a12d2},
    "Places::BulkNameFetchingJob" => {:slice, :a12d2},
    "Places::DeleteIfOrphanJob" => {:slice, :a12d2},
    "Places::NameFetchingJob" => {:slice, :a12d2},
    "Places::OrphanCleanupJob" => {:slice, :a12d2},
    "Points::AnomalyBackfillUserJob" => {:slice, :a12d1},
    "Points::AnomalyFilterJob" => {:slice, :a12d1},
    "Points::NightlyReverseGeocodingJob" => {:slice, :a12d2},
    "Points::RawData::ArchiveJob" => {:oban, ["cron:raw_data_archive_job"]},
    "Points::RawData::ArchiveUserJob" => {:oban, ["cron:raw_data_archive_job"]},
    "Points::RawData::ClearJob" => {:oban, ["cron:raw_data_clear_job"]},
    "Points::RawData::ClearUserJob" => {:oban, ["cron:raw_data_clear_job"]},
    "Points::RawData::VerifyRandomJob" => {:oban, ["cron:raw_data_verify_job"]},
    "Posters::CreateJob" => {:slice, :a9},
    "ReverseGeocodingJob" =>
      {:oban, ["command:geocoding.reverse_point", "command:geocoding.reverse_place"]},
    "RouteVideos::PurgeJob" => {:slice, :a8},
    "StaleJobsRecoveryJob" => {:slice, :a7},
    "Stats::CalculatingJob" => {:oban, ["command:stats.calculate_month"]},
    "Stats::FullRecalculationJob" => {:slice, :a12d1},
    "Stats::ToponymsRefreshJob" => {:oban, ["cron:stats_toponyms_refresh_job"]},
    "TeslaMate::SyncJob" => {:slice, :a7},
    "TeslaMate::SyncSchedulingJob" => {:slice, :a7},
    "TrackSegments::TimeAnchorBackfillJob" => {:oban, ["command:release.time_anchor"]},
    "Tracks::BackfillGenerationJob" => {:slice, :a12d2},
    "Tracks::BoundaryResolverJob" => {:oban, ["command:tracks.generate_range"]},
    "Tracks::DailyGenerationJob" => {:oban, ["cron:daily_track_generation_job"]},
    "Tracks::DeduplicationJob" => {:oban, ["command:release.tracks_dedup"]},
    "Tracks::ParallelGeneratorJob" => {:oban, ["command:tracks.generate_range"]},
    "Tracks::RealtimeGenerationJob" => {:oban, ["command:tracks.generate_realtime"]},
    "Tracks::RecalculateJob" =>
      {:oban, ["command:tracks.recalculate", "command:points.anomaly_recalculate"]},
    "Tracks::ThrottledBackfillJob" => {:slice, :a12d2},
    "Tracks::TimeChunkProcessorJob" => {:oban, ["command:tracks.generate_range"]},
    "TransportationModes::FleetReclassifyJob" => {:oban, ["command:release.transportation"]},
    "TransportationModes::ImportBackfillJob" => {:slice, :a7},
    "TransportationModes::ReclassifyTrackJob" =>
      {:oban, ["command:transportation.reclassify_track"]},
    "TransportationModes::UserReclassifyJob" => {:slice, :a12d2},
    "Trek::ImportTripsJob" => {:slice, :a7},
    "Trek::SyncJob" => {:slice, :a7},
    "Trek::SyncSchedulingJob" => {:slice, :a7},
    "Trips::CalculateAllJob" => {:oban, ["command:trips.calculate"]},
    "Trips::CalculateCountriesJob" => {:oban, ["command:trips.calculate"]},
    "Trips::CalculateDistanceJob" => {:oban, ["command:trips.calculate"]},
    "Trips::CalculatePathJob" => {:oban, ["command:trips.calculate"]},
    "Users::CreationWebhookJob" => {:slice, :a12d2},
    "Users::DestroyJob" => {:slice, :a12d2},
    "Users::DestructionWebhookJob" => {:slice, :a12d2},
    "Users::Digests::CalculatingJob" => :retire,
    "Users::Digests::EmailSendingJob" => :retire,
    "Users::Digests::Monthly::CalculatingJob" => {:slice, :a12d1},
    "Users::Digests::Monthly::EmailSendingJob" => {:slice, :a12c},
    "Users::Digests::Monthly::SchedulingJob" => {:slice, :a12d1},
    "Users::Digests::Yearly::CalculatingJob" => {:slice, :a12d1},
    "Users::Digests::Yearly::EmailSendingJob" => {:slice, :a12c},
    "Users::Digests::Yearly::SchedulingJob" => {:slice, :a12d1},
    "Users::ExportDataJob" => {:slice, :a7},
    "Users::ImportDataJob" => {:slice, :a7},
    "Users::MailerSendingJob" => {:oban, @mail, :retire},
    "Users::PointsCounterCorrectionJob" => {:oban, ["cron:points_counter_correction_job"]},
    "Users::RecalculateDataJob" => {:slice, :a12d1},
    "Users::ResetPointsCounterJob" => :retire,
    "VisitSuggestingJob" => {:oban, ["command:visits.suggest"]},
    "Visits::FleetRedetectJob" => {:oban, ["command:release.visits_fleet_redetect"]},
    "Visits::FullHistoryRedetectJob" => {:oban, ["command:visits.full_history_redetect"]},
    "Visits::UserRedetectJob" => {:slice, :a12d2}
  }

  def owners, do: @owners
  def classes, do: Map.keys(@owners)
  def slices, do: @slices
end
