defmodule Mix.Tasks.Dawarich.FrontendInventory do
  @moduledoc false
  use Mix.Task

  alias Dawarich.Build.FrontendInventory

  @start "<!-- inventory:start -->"
  @stop "<!-- inventory:end -->"

  @impl true
  def run(args) do
    {opts, []} = OptionParser.parse!(args, strict: [out: :string])
    out = Keyword.get(opts, :out, "../docs/phoenix/native-frontend-inventory.md")
    findings = FrontendInventory.scan(File.cwd!())
    existing = if File.exists?(out), do: File.read!(out), else: "#{@start}\n#{@stop}\n"
    [head, rest] = String.split(existing, @start, parts: 2)
    [_old, tail] = String.split(rest, @stop, parts: 2)
    File.write!(out, [head, @start, "\n", render(findings), @stop, tail])
    Mix.shell().info("wrote #{length(findings)} findings to #{out}")
  end

  defp render(findings) do
    {tests, sources} = Enum.split_with(findings, &(&1.kind == :markup_assertion))

    [
      "Generated by `mix dawarich.frontend_inventory`.\n\n",
      summary(findings),
      "\n### Sources\n\n| File | Hotwire | Findings |\n| --- | --- | --- |\n",
      Enum.map(group(sources), &source_row/1),
      "\n### Tests with markup assertions\n\n| Test file | Assertions |\n| --- | --- |\n",
      Enum.map(group(tests), fn {file, list} -> "| `#{file}` | #{length(list)} |\n" end),
      "\n"
    ]
  end

  defp summary(findings) do
    rows =
      findings
      |> Enum.frequencies_by(& &1.kind)
      |> Enum.sort()
      |> Enum.map(fn {kind, count} -> "| #{kind} | #{count} |\n" end)

    ["| Kind | Count |\n| --- | --- |\n" | rows]
  end

  defp group(findings), do: findings |> Enum.group_by(& &1.file) |> Enum.sort()

  defp source_row({file, list}) do
    hotwire = if Enum.any?(list, &FrontendInventory.hotwire?/1), do: "yes", else: "no"
    values = Enum.map_join(list, ", ", &"#{&1.kind}:#{&1.value}")
    "| `#{file}` | #{hotwire} | #{values} |\n"
  end
end
