---
:concurrency: <%= ENV.fetch("BACKGROUND_PROCESSING_CONCURRENCY", 10) %>
:queues:
  - highest_priority
  - data_migrations
  - points
  - default
  - mailers
  - families
  - imports
  - exports
  - tracks
  - stats
  - trips
  - reverse_geocoding
  - visit_suggesting
  - places
  - posters
  - app_version_checking
  - cache
  - archival
  - digests
  - achievements
  - low_priority
