const defaultTheme = require("tailwindcss/defaultTheme")

module.exports = {
  content: [
    "./app/helpers/**/*.rb",
    "./app/javascript/**/*.js",
    "./app/views/**/*.{erb,haml,html,slim}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter var", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [
    require("daisyui"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/typography"),
  ],
  daisyui: {
    themes: [
      {
        dawarich: {
          "primary": "#3B82F6",
          "primary-content": "#FFFFFF",
          "secondary": "#0D9488",
          "secondary-content": "#FFFFFF",
          "accent": "#0D9488",
          "accent-content": "#FFFFFF",
          "neutral": "#1A1A1A",
          "neutral-content": "#EAEAEA",
          "base-100": "#FFFFFF",
          "base-200": "#F5F5F3",
          "base-300": "#E5E5E2",
          "base-content": "#1A1A1A",
          "info": "#06B6D4",
          "info-content": "#FFFFFF",
          "success": "#0D9488",
          "success-content": "#FFFFFF",
          "warning": "#F59E0B",
          "warning-content": "#FFFFFF",
          "error": "#EF4444",
          "error-content": "#FFFFFF",
          "--rounded-btn": "0.375rem",
          "--rounded-box": "0.625rem",
          "--rounded-badge": "9999px",
        },
        "dawarich-dark": {
          "primary": "#60A5FA",
          "primary-content": "#0A1530",
          "secondary": "#2DD4BF",
          "secondary-content": "#0A1510",
          "accent": "#2DD4BF",
          "accent-content": "#0A1510",
          "neutral": "#EAEAEA",
          "neutral-content": "#141414",
          "base-100": "#1C1C1C",
          "base-200": "#141414",
          "base-300": "#101010",
          "base-content": "#EAEAEA",
          "info": "#22D3EE",
          "info-content": "#0A1520",
          "success": "#2DD4BF",
          "success-content": "#0A1510",
          "warning": "#FBBF24",
          "warning-content": "#1A1505",
          "error": "#F87171",
          "error-content": "#1A0A0A",
          "--rounded-btn": "0.375rem",
          "--rounded-box": "0.625rem",
          "--rounded-badge": "9999px",
        },
      },
    ],
  },
}
