---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dawarich
  name: photon-data
  labels:
    storage.k8s.io/name: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi
