---
apiVersion: v1
kind: Service
metadata:
  namespace: dawarich
  labels:
    service: photon
  name: photon
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2322
  selector:
    app: photon
