# frozen_string_literal: true

module ApiSharedGoldenOracle
  CASES = [
    { name: 'phrase_required', action: 'trip', link: { magic_phrase: 'synthetic-phrase' }, status: 401,
      json: { 'error' => 'unauthorized' } },
    { name: 'phrase_unlocked', action: 'trip', link: { magic_phrase: 'synthetic-phrase' }, cookie: :current },
    { name: 'phrase_rotated', action: 'trip', link: { magic_phrase: 'rotated-phrase' }, cookie: :old,
      status: 401, json: { 'error' => 'unauthorized' } },
    { name: 'trip_metadata', action: 'trip', json: { 'name' => 'Synthetic shared trip',
      'started_at' => '2026-03-29T01:00:00.000+01:00', 'ended_at' => '2026-03-29T03:00:00.000+02:00' } },
    { name: 'trip_uuid_uppercase', action: 'trip', path: "/api/v1/shared/#{LINK.upcase}/trip" },
    { name: 'trip_uuid_compact', action: 'trip', path: "/api/v1/shared/#{LINK.delete('-')}/trip" },
    { name: 'trip_stats_km', action: 'trip', link: { settings: { 'show_stats' => true } }, distance: 123 },
    { name: 'trip_stats_mi', action: 'trip', link: { settings: { 'show_stats' => true } },
      user: { distance_unit: 'mi' }, distance: 77 },
    { name: 'trip_stats_string', action: 'trip', link: { settings: { 'show_stats' => 'true' } }, no_distance: true },
    { name: 'trip_stats_null_distance', action: 'trip', link: { settings: { 'show_stats' => true } },
      trip: { distance: nil }, no_distance: true },
    { name: 'trip_gone', action: 'trip', link: { resource_id: 959_999 }, status: 410,
      json: { 'error' => 'gone' } },
    { name: 'trip_foreign_resource', action: 'trip', link: { resource_id: 951_102 }, status: 410,
      json: { 'error' => 'gone' } },
    { name: 'trip_pending_owner', action: 'trip', user: { status: 3 } },
    { name: 'trip_locale_independent', action: 'trip', query: '?locale=de',
      headers: { 'Accept-Language' => 'de' } },
    { name: 'trip_unsupported_query_shape', action: 'trip', query: '?unused[]=x', expect: :rails },
    { name: 'trip_unsupported_client_header', action: 'trip', headers: { 'X-Dawarich-Client' => 'ios' },
      expect: :rails },
    { name: 'trip_conditional', action: 'trip', conditional: true, status: 304 },
    { name: 'trip_head', action: 'trip', method: :head, expect: :rails },
    { name: 'trip_cloud', action: 'trip', env: { 'SELF_HOSTED' => 'false' }, expect: :rails },
    { name: 'points_trip_edges', action: 'points', timestamps: [T0, T0 + 3600], cache: 'max-age=30, public' },
    { name: 'points_track_relation', action: 'points', link: { resource_type: 1, resource_id: 951_201 },
      timestamps: [T0 - 1, T0 + 3601], cache: 'max-age=30, public' },
    { name: 'points_trip_gone', action: 'points', link: { resource_id: 959_999 }, json: [] },
    { name: 'points_track_gone', action: 'points', link: { resource_type: 1, resource_id: 959_999 }, json: [] },
    { name: 'points_timeline_dst', action: 'points', seed: :timeline, user: { timezone: 'Europe/Berlin' },
      link: { resource_type: 2, resource_id: nil,
        settings: { 'start_date' => '2026-03-29', 'end_date' => '2026-03-29' } },
      timestamps: [T0 - 3600, T0 + 79_199] },
    { name: 'points_timeline_invalid', action: 'points', link: { resource_type: 2, resource_id: nil,
      settings: { 'start_date' => 'invalid', 'end_date' => '2026-03-29' } }, json: [], expect: :rails },
    { name: 'points_privacy', action: 'points', seed: :privacy, timestamps: [T0, T0 + 3600] },
    { name: 'points_privacy_boundary', action: 'points', seed: :boundary,
      timestamps: [T0, T0 + 32, T0 + 33, T0 + 3600] },
    { name: 'points_10000', action: 'points', seed: :many, count: 10_000, size: 10_000 },
    { name: 'points_10001', action: 'points', seed: :many, count: 10_001, size: 5001 },
    { name: 'points_privacy_before_stride', action: 'points', seed: :private_many,
      count: 10_001, size: 10_000 },
    { name: 'points_phrase_private', action: 'points', link: { magic_phrase: 'synthetic-phrase' },
      cookie: :current, timestamps: [T0, T0 + 3600], cache: 'max-age=0, private, must-revalidate' },
    { name: 'points_conditional', action: 'points', conditional: true, status: 304 },
    { name: 'points_json_suffix', action: 'points.json', expect: :rails, timestamps: [T0, T0 + 3600] },
    { name: 'live_899', action: 'points', seed: :live, age: 899,
      link: { resource_type: 3, resource_id: nil }, timestamps: [NOW.to_i - 899] },
    { name: 'live_900', action: 'points', seed: :live, age: 900,
      link: { resource_type: 3, resource_id: nil }, timestamps: [NOW.to_i - 900] },
    { name: 'live_901', action: 'points', seed: :live, age: 901,
      link: { resource_type: 3, resource_id: nil }, json: [] },
    { name: 'live_latest_private', action: 'points', seed: :live_private, age: 1,
      link: { resource_type: 3, resource_id: nil }, json: [] },
    { name: 'live_empty', action: 'points', seed: :empty, link: { resource_type: 3, resource_id: nil }, json: [] },
    { name: 'route_trip_empty', action: 'route', json: [], cache: 'max-age=30, public' },
    { name: 'route_track_empty', action: 'route', link: { resource_type: 1, resource_id: 951_201 }, json: [] },
    { name: 'route_live_created_cutoff', action: 'route', seed: :route,
      link: { resource_type: 3, resource_id: nil, settings: { 'show_route' => true } },
      timestamps: [Time.parse("#{STAMP} UTC").to_i, Time.parse("#{STAMP} UTC").to_i + 1] },
    { name: 'route_live_string_true', action: 'route', seed: :route,
      link: { resource_type: 3, resource_id: nil, settings: { 'show_route' => 'yes' } }, size: 2 },
    { name: 'route_live_string_false', action: 'route', seed: :route,
      link: { resource_type: 3, resource_id: nil, settings: { 'show_route' => '0' } }, json: [] },
    { name: 'route_live_unset', action: 'route', seed: :route,
      link: { resource_type: 3, resource_id: nil }, json: [] },
    { name: 'photos_disabled', action: 'photos', json: [] },
    { name: 'photos_disabled_provider', action: 'photos', seed: :provider, json: [], no_fetch: true },
    { name: 'thumbnail_disabled_provider', action: 'photos/public-100/thumbnail', seed: :provider,
      query: '?source=immich', status: 404, no_fetch: true },
    { name: 'thumbnail_disabled', action: 'photos/public-0/thumbnail', query: '?source=immich', status: 404 },
    { name: 'photos_string_flag', action: 'photos', link: { settings: { 'show_photos' => 'true' } }, json: [] },
    { name: 'photos_unconfigured', action: 'photos', link: { settings: { 'show_photos' => true } },
      expect: :rails, json: [], cache: 'max-age=60, public', acl: [] },
    { name: 'thumbnail_unconfigured', action: 'photos/unknown/thumbnail', query: '?source=immich',
      link: { settings: { 'show_photos' => true } }, expect: :rails, status: 404, acl: [] },
    { name: 'photos_phrase_unconfigured', action: 'photos',
      link: { magic_phrase: 'synthetic-phrase', settings: { 'show_photos' => true } }, cookie: :current,
      expect: :rails, json: [], cache: 'max-age=0, private, must-revalidate', acl: [] },
    { name: 'photos_provider_cap', action: 'photos', seed: :provider,
      link: { settings: { 'show_photos' => true } }, expect: :rails, size: 100, acl_size: 101 },
    { name: 'photos_provider_conditional', action: 'photos', seed: :provider, conditional: true,
      link: { settings: { 'show_photos' => true } }, expect: :rails, status: 304, acl_size: 101,
      cache: 'max-age=60, public' },
    { name: 'photos_provider_track_cap', action: 'photos', seed: :provider,
      link: { resource_type: 1, resource_id: 951_201, settings: { 'show_photos' => true } },
      expect: :rails, size: 100, acl_size: 100 },
    { name: 'thumbnail_trip_beyond_marker_cap', action: 'photos/public-100/thumbnail', query: '?source=immich',
      seed: :provider, link: { settings: { 'show_photos' => true } }, expect: :rails, jpeg: true, acl_size: 101 },
    { name: 'thumbnail_track_beyond_marker_cap', action: 'photos/public-100/thumbnail', query: '?source=immich',
      seed: :provider, link: { resource_type: 1, resource_id: 951_201, settings: { 'show_photos' => true } },
      expect: :rails, status: 404, acl_size: 100 },
    { name: 'thumbnail_private', action: 'photos/private/thumbnail', query: '?source=immich', seed: :provider,
      link: { settings: { 'show_photos' => true } }, expect: :rails, status: 404, acl_size: 101 },
    { name: 'thumbnail_foreign', action: 'photos/foreign/thumbnail', query: '?source=immich', seed: :provider,
      link: { settings: { 'show_photos' => true } }, expect: :rails, status: 404, acl_size: 101 },
    { name: 'thumbnail_provider_failed', action: 'photos/public-100/thumbnail', query: '?source=immich',
      seed: :provider, upstream_status: 503, link: { settings: { 'show_photos' => true } },
      expect: :rails, status: 404, acl_size: 101 }
  ].concat(ACTIONS.flat_map do |action|
    [{ name: "missing_#{action}", action:, missing: true, status: 404, json: { 'error' => 'not_found' } },
     { name: "revoked_#{action}", action:, link: { revoked_at: STAMP }, status: 404,
       json: { 'error' => 'not_found' } },
     { name: "expired_#{action}", action:, link: { expires_at: NOW }, status: 404,
       json: { 'error' => 'not_found' } }]
  end).freeze
end
