# frozen_string_literal: true

module ApiVisitsGoldenOracle
  CREATE = { name: 'Synthetic created visit', latitude: 52.52, longitude: 13.405,
             started_at: '2026-09-10T12:00:00Z', ended_at: '2026-09-10T13:01:59Z' }.freeze
  SAME = CREATE.merge(name: 'Visit 1', started_at: '2026-09-01T12:00:00Z', ended_at: '2026-09-01T13:00:00Z').freeze
  PHOTON = { name: 'Selected synthetic', latitude: 52.5201, longitude: 13.4051,
             osm_id: 42, geodata: { properties: { osm_id: 42, osm_type: 'N' } } }.freeze
  RANGE = 'start_at=2026-09-01T12:00:00Z&end_at=2026-09-04T12:00:00Z'
  BOX = 'selection=true&sw_lat=52&sw_lng=13&ne_lat=53&ne_lng=14'
  CASES = [
    { name: 'destroy', method: :delete, path: H, status: 204, tombstone: true, jobs: 1 },
    { name: 'destroy_demo', method: :delete, path: H, status: 204, seed: :demo, tombstone: true, jobs: 0 },
    { name: 'index_time', path: "#{P}?#{RANGE}", ids: [953_301, 953_302, 953_303, 953_304, 953_310] },
    { name: 'index_time_invalid', path: "#{P}?start_at=bad&end_at=bad", status: 400 },
    { name: 'index_time_missing', path: P, status: 400 },
    { name: 'index_bbox', path: "#{P}?#{BOX}", ids: [953_302, 953_301] },
    { name: 'index_bbox_area', path: "#{P}?#{BOX}", seed: :area_inside, ids: [953_310, 953_302, 953_301] },
    { name: 'index_bbox_time', path: "#{P}?#{BOX}&#{RANGE}", ids: [953_302, 953_301] },
    { name: 'index_bbox_edge', path: "#{P}?selection=true&sw_lat=52.52&sw_lng=13.405&ne_lat=53&ne_lng=14", ids: [] },
    { name: 'index_bbox_partial', path: "#{P}?selection=true&sw_lat=52&#{RANGE}",
      ids: [953_301, 953_302, 953_303, 953_304, 953_310] },
    { name: 'index_page', path: "#{P}?#{RANGE}&page=2&per_page=2", ids: [953_303, 953_304],
      headers: { 'x-current-page' => '2', 'x-total-pages' => '3', 'x-total-count' => '5' } },
    { name: 'index_page_cap', path: "#{P}?#{RANGE}&page=1&per_page=501", count: 5 },
    { name: 'index_page_empty', path: "#{P}?#{RANGE}&page=99", ids: [] },
    { name: 'show', path: H, fields: { 'confidence' => 39, 'confidence_band' => 'low' } },
    { name: 'show_40', path: "#{P}/953302", fields: { 'confidence' => 40, 'confidence_band' => 'medium' } },
    { name: 'show_69', path: "#{P}/953303", fields: { 'confidence' => 69, 'confidence_band' => 'medium' } },
    { name: 'show_70', path: "#{P}/953304", fields: { 'confidence' => 70, 'confidence_band' => 'high' } },
    { name: 'show_nil', path: "#{P}/953310", fields: { 'confidence' => nil, 'confidence_band' => nil } },
    { name: 'show_conditional', path: H, conditional: true, status: 304 },
    { name: 'show_berlin', path: H, user: { timezone: 'Europe/Berlin' } },
    { name: 'create', method: :post, path: P, body: { visit: CREATE }, fields: { 'duration' => 61 }, created: true },
    { name: 'create_new_place', method: :post, path: P,
      body: { visit: CREATE.merge(latitude: 51, longitude: 12) }, created: true, new_place: true },
    { name: 'create_duplicate', method: :post, path: P, body: { visit: SAME }, fields: { 'id' => 953_301 } },
    { name: 'create_conflict', method: :post, path: P, body: { visit: SAME.merge(name: 'Conflict') }, status: 422 },
    { name: 'create_revive_deleted', method: :post, path: P, seed: :deleted,
      body: { visit: SAME }, revived: true },
    { name: 'create_revive_declined', method: :post, path: P, seed: :declined,
      body: { visit: SAME }, revived: true },
    { name: 'create_suggested_deleted', method: :post, path: P, seed: :deleted,
      body: { visit: SAME.merge(status: 'suggested') }, status: 422 },
    { name: 'create_suggested_new_place', method: :post, path: P, provider: true,
      body: { visit: CREATE.merge(latitude: 51, longitude: 12, status: 'suggested') },
      created: true, new_place: true, jobs: 1 },
    { name: 'create_root_replay', method: :post, path: P, body: CREATE, expect: :rails, status: 422 },
    { name: 'create_kill_replay', method: :post, path: P, body: { visit: CREATE }, expect: :rails,
      env: { 'DAWARICH_RAILS_SLICES' => 'api_visits' }, created: true },
    { name: 'create_bad_time', method: :post, path: P, body: { visit: CREATE.merge(started_at: 'bad') }, status: 422 },
    { name: 'create_time_equal', method: :post, path: P,
      body: { visit: CREATE.merge(ended_at: CREATE[:started_at]) }, status: 422 },
    { name: 'create_missing_coordinate', method: :post, path: P,
      body: { visit: CREATE.except(:longitude) }, status: 422 },
    { name: 'create_bad_coordinate', method: :post, path: P,
      body: { visit: CREATE.merge(latitude: 'bad') }, status: 422 },
    { name: 'create_out_of_range', method: :post, path: P,
      body: { visit: CREATE.merge(latitude: 91) }, status: 422 },
    { name: 'create_zero', method: :post, path: P,
      body: { visit: CREATE.merge(latitude: 0, longitude: 0) }, created: true, new_place: true },
    { name: 'update_name', method: :patch, path: H, body: { visit: { name: 'Edited' } },
      fields: { 'name' => 'Edited' } },
    { name: 'update_put', method: :put, path: H, body: { visit: { name: 'Put name' } } },
    { name: 'update_suggested', method: :patch, path: "#{P}/953302", body: { visit: { name: 'Asserted' } },
      fields: { 'status' => 'confirmed' } },
    { name: 'update_explicit_suggested', method: :patch, path: "#{P}/953302",
      body: { visit: { name: 'Explicit', status: 'suggested' } }, fields: { 'status' => 'suggested' } },
    { name: 'update_decline', method: :patch, path: H, body: { visit: { status: 'declined' } }, jobs: 1 },
    { name: 'update_place', method: :patch, path: H, body: { visit: { place_id: 953_202 } },
      fields: { 'name' => 'Place 2' }, jobs: 1 },
    { name: 'update_suggested_foreign_place', method: :patch, path: H,
      body: { visit: { place_id: 953_203 } }, fields: { 'name' => 'Place 3' }, jobs: 1 },
    { name: 'update_bad_place', method: :patch, path: H, body: { visit: { place_id: 959_999 } }, status: 422 },
    { name: 'update_foreign_area', method: :patch, path: H, body: { visit: { area_id: 953_102 } }, status: 422 },
    { name: 'update_area', method: :patch, path: H,
      body: { visit: { area_id: 953_101 } }, fields: { 'name' => 'Synthetic area' } },
    { name: 'update_area_explicit_name', method: :patch, path: H,
      body: { visit: { area_id: 953_101, name: 'Explicit area name' } }, fields: { 'name' => 'Explicit area name' } },
    { name: 'update_ignored_coordinates', method: :patch, path: H,
      body: { visit: { latitude: 0, longitude: 0 } } },
    { name: 'update_month', method: :patch, path: H,
      body: { visit: { started_at: '2026-08-31T23:30:00Z', ended_at: '2026-09-01T13:00:00Z' } }, months: true },
    { name: 'update_month_berlin', method: :patch, path: H, user: { timezone: 'Europe/Berlin' },
      body: { visit: { started_at: '2026-08-31T23:30:00Z', ended_at: '2026-09-01T13:00:00Z' } }, months: :berlin },
    { name: 'update_demo_adopt', method: :patch, path: H, seed: :adopt,
      body: { visit: { name: 'Adopted', place_id: 953_202 } }, adopted: true },
    { name: 'merge', method: :post, path: "#{P}/merge", body: { visit_ids: [953_302, 953_301] }, merged: true },
    { name: 'merge_too_few', method: :post, path: "#{P}/merge", body: { visit_ids: [953_301] }, status: 422 },
    { name: 'merge_duplicate_ids', method: :post, path: "#{P}/merge",
      body: { visit_ids: [953_301, 953_301] }, status: 404 },
    { name: 'merge_foreign', method: :post, path: "#{P}/merge", body: { visit_ids: [953_301, 953_309] }, status: 404 },
    { name: 'bulk_partial', method: :post, path: "#{P}/bulk_update",
      body: { visit_ids: [953_301, 953_309, 959_999], status: 'suggested' }, fields: { 'updated_count' => 1 } },
    { name: 'bulk_decline', method: :post, path: "#{P}/bulk_update",
      body: { visit_ids: [953_301, 953_302], status: 'declined' }, fields: { 'updated_count' => 2 }, jobs: 1 },
    { name: 'bulk_none', method: :post, path: "#{P}/bulk_update",
      body: { visit_ids: [], status: 'confirmed' }, status: 422 },
    { name: 'bulk_hidden', method: :post, path: "#{P}/bulk_update",
      body: { visit_ids: [953_305, 953_306], status: 'confirmed' }, status: 422 },
    { name: 'bulk_bad_status', method: :post, path: "#{P}/bulk_update",
      body: { visit_ids: [953_301], status: 'bad' }, status: 422 },
    { name: 'batch_mixed', method: :post, path: "#{P}/batch", body: { visits: [CREATE, SAME, {}, 'bad'] },
      fields: { 'created_count' => 1, 'duplicate_count' => 1, 'failed_count' => 2 } },
    { name: 'batch_deleted', method: :post, path: "#{P}/batch", seed: :deleted,
      body: { visits: [SAME.merge(status: 'suggested')] }, fields: { 'failed_count' => 1 } },
    { name: 'batch_100', method: :post, path: "#{P}/batch", body: { visits: Array.new(100) { SAME } },
      fields: { 'duplicate_count' => 100, 'created_count' => 0, 'failed_count' => 0 } },
    { name: 'batch_101', method: :post, path: "#{P}/batch", body: { visits: Array.new(101) { SAME } }, status: 422,
      fields: { 'limit' => 100, 'requested' => 101 } },
    { name: 'batch_empty', method: :post, path: "#{P}/batch", body: { visits: [] }, status: 422 },
    { name: 'possible_disabled', path: "#{H}/possible_places", expect: :rails, count: 1 },
    { name: 'possible_current_prepend', path: "#{H}/possible_places", provider: true, expect: :rails, count: 2 },
    { name: 'select_new', method: :post, path: "#{H}/select_place",
      body: { photon: PHOTON }, status: 201, selected: true },
    { name: 'select_dedup_tags', method: :post, path: "#{H}/select_place",
      body: { photon: PHOTON.merge(name: 'Place 2') }, status: 201, selected: true, dedup: true },
    { name: 'select_no_geodata', method: :post, path: "#{H}/select_place", store_geodata: false,

      body: { photon: PHOTON }, status: 201, selected: true },
    { name: 'select_missing_name', method: :post, path: "#{H}/select_place",
      body: { photon: PHOTON.except(:name) }, status: 422 },
    { name: 'select_bad_lat', method: :post, path: "#{H}/select_place",
      body: { photon: PHOTON.merge(latitude: 91) }, status: 422 },
    { name: 'auth_none', path: H, auth: :none, status: 401 },
    { name: 'auth_unknown', path: H, auth: :unknown, status: 401 },
    { name: 'auth_pending', path: H, user: { status: 3 }, status: 402 },
    { name: 'auth_query', path: H, auth: :query },
    { name: 'replay_head', path: H, method: :head, expect: :rails },
    { name: 'replay_format', path: "#{H}?format=xml", expect: :rails },
    { name: 'replay_suffix', path: "#{H}.json", expect: :rails },
    { name: 'replay_kill', path: H, env: { 'DAWARICH_RAILS_SLICES' => 'api_visits' }, expect: :rails },
    { name: 'replay_cloud', path: H, env: { 'SELF_HOSTED' => 'false' }, expect: :rails },
    { name: 'replay_query_shape', path: "#{H}?unused[]=x", expect: :rails }
  ].concat(%w[show destroy possible_places select_place].flat_map do |action|
    [953_305, 953_306, 953_309, 959_999].map do |id|
      method = { 'destroy' => :delete, 'select_place' => :post }.fetch(action, :get)
      { name: "#{action}_hidden_#{id}",
        path: "#{P}/#{id}#{"/#{action}" if %w[possible_places select_place].include?(action)}",
        method:, status: 404, **(action == 'select_place' ? { body: { photon: PHOTON } } : {}) }
    end
  end).freeze
end
