# frozen_string_literal: true

module ApiAccountGoldenOracle
  EXIST = '/api/v1/users/exist'
  PASSWORD = 'a4rest-account-synthetic-password'
  WEBHOOK = 'a4rest-account-synthetic-webhook'
  CASES = [
    { name: 'me_pending', path: P, user: { status: 3 }, status: 402, error: 'payment_required' },
    { name: 'me_defaults', path: P, me: true },
    { name: 'me_berlin', path: P, me: true, user: { timezone: 'Europe/Berlin' } },
    { name: 'me_inactive', path: P, me: true, user: { status: 0 } },
    { name: 'me_trial', path: P, me: true, user: { status: 2 } },
    { name: 'me_cloud', path: P, me: true, env: { 'SELF_HOSTED' => 'false' }, expect: :rails },
    { name: 'me_geocoding', path: P, me: true, geocoding: true },
    { name: 'me_settings', path: P, me: true,
      user: { settings: { 'timezone' => 'UTC', 'maps' => { 'distance_unit' => 'mi' }, 'route_opacity' => 0.7 } } },
    { name: 'me_settings_casts', path: P, me: true,
      user: { settings: { 'timezone' => 'UTC', 'fog_of_war_meters' => '-7suffix',
                          'meters_between_routes' => '-20', 'minutes_between_routes' => '2000',
                          'time_threshold_minutes' => '-2', 'merge_threshold_minutes' => '7.9',
                          'live_map_enabled' => false, 'speed_colored_routes' => 'false',
                          'route_opacity' => '0.7tail', 'visits_suggestions_enabled' => true,
                          'globe_projection' => 'off' } } },
    { name: 'me_maps', path: P, me: true,
      user: { settings: { 'timezone' => 'UTC',
                          'maps' => { 'distance_unit' => 'mi', 'disabled_poi_groups' => ['shops'],
                                      'hidden_tile_categories' => ['airport'],
                                      'custom' => { 'long_name' => true, 'a' => 1 } } } } },
    { name: 'me_no_auth', path: P, auth: :none, status: 401 },
    { name: 'me_unknown_auth', path: P, auth: :unknown, status: 401 },
    { name: 'me_deleted', path: P, user: { deleted_at: STAMP }, status: 401 },
    { name: 'me_query_auth', path: P, auth: :query, me: true },
    { name: 'me_conditional', path: P, conditional: true, status: 304 },
    { name: 'exist_missing_config', method: :post, path: EXIST, auth: :none, webhook: :missing, status: 503,
      body: { ids: [OWNER] }, error: 'Configuration error' },
    { name: 'exist_missing_secret', method: :post, path: EXIST, auth: :none, status: 401, body: { ids: [OWNER] } },
    { name: 'exist_invalid_secret', method: :post, path: EXIST, auth: :none, status: 401,
      headers: { 'X-Webhook-Secret' => 'invalid' }, body: { ids: [OWNER] } },
    { name: 'exist_nil', method: :post, path: EXIST, auth: :none, manager: true, status: 422,
      body: { ids: nil }, error: 'ids is required' },
    { name: 'exist_missing', method: :post, path: EXIST, auth: :none, manager: true, status: 422, body: {} },
    { name: 'exist_array', method: :post, path: EXIST, auth: :none, manager: true,
      body: { ids: [OTHER, OWNER, 959_999, OWNER, nil, 'bad', ' 954001 ', '954001x'] },
      json: { 'existing' => [OWNER, OTHER], 'missing' => [959_999] } },
    { name: 'exist_empty', method: :post, path: EXIST, auth: :none, manager: true,
      body: { ids: [] }, json: { 'existing' => [], 'missing' => [] } },
    { name: 'exist_scalar', method: :post, path: EXIST, auth: :none, manager: true,
      body: { ids: OWNER.to_s }, json: { 'existing' => [OWNER], 'missing' => [] } },
    { name: 'exist_deleted', method: :post, path: EXIST, auth: :none, manager: true,
      user: { deleted_at: STAMP }, body: { ids: [OWNER, OTHER] },
      json: { 'existing' => [OTHER], 'missing' => [OWNER] } },
    { name: 'delete_password', method: :delete, path: P, password: :valid, expect: :rails, deleted: true, jobs: 1 },
    { name: 'delete_missing_password', method: :delete, path: P, expect: :rails, status: 401,
      error: 'password_required' },
    { name: 'delete_wrong_password', method: :delete, path: P, password: :wrong, expect: :rails, status: 401 },
    { name: 'delete_pending', method: :delete, path: P, password: :valid,
      user: { status: 3 }, expect: :rails, deleted: true, jobs: 1 },
    { name: 'delete_oauth_email', method: :delete, path: P, seed: :oauth, expect: :rails,
      body: { confirm_email: ' A4REST-ACCOUNT@EXAMPLE.INVALID ' }, deleted: true, jobs: 1 },
    { name: 'delete_oauth_bad_email', method: :delete, path: P, seed: :oauth, expect: :rails,
      body: { confirm_email: 'wrong@example.invalid' }, status: 401 },
    { name: 'delete_family_guard', method: :delete, path: P, seed: :family, password: :valid,
      expect: :rails, status: 422, error: 'cannot_delete_account' },
    { name: 'delete_family_single', method: :delete, path: P, seed: :single_family, password: :valid,
      expect: :rails, deleted: true, jobs: 1 },
    { name: 'delete_twice', method: :delete, path: P, password: :valid,
      expect: :rails, repeat: true, status: 401, deleted: true, jobs: 1 },
    { name: 'delete_cloud', method: :delete, path: P, expect: :rails,
      env: { 'SELF_HOSTED' => 'false' }, status: 202, jobs: 1, cloud_delete: true },
    { name: 'delete_cloud_twice', method: :delete, path: P, expect: :rails,
      env: { 'SELF_HOSTED' => 'false' }, status: 429, repeat: true, jobs: 1, cloud_delete: true },
    { name: 'otp_setup', method: :post, path: "#{T}/setup", password: :valid,
      expect: :rails, crypto: :setup },
    { name: 'otp_setup_rotation', method: :post, path: "#{T}/setup", password: :valid,
      otp: :provisioned, expect: :rails, crypto: :setup },
    { name: 'otp_setup_enabled', method: :post, path: "#{T}/setup", password: :valid,
      otp: :enabled, expect: :rails, status: 409, error: 'two_factor_already_enabled' },
    { name: 'otp_setup_password', method: :post, path: "#{T}/setup", expect: :rails,
      status: 401, error: 'password_required' },
    { name: 'otp_confirm', method: :post, path: "#{T}/confirm", password: :valid,
      otp: :provisioned, code: :current, expect: :rails, crypto: :confirm },
    { name: 'otp_confirm_bad', method: :post, path: "#{T}/confirm", password: :valid,
      otp: :provisioned, code: :bad, expect: :rails, status: 422, error: 'invalid_otp' },
    { name: 'otp_confirm_no_secret', method: :post, path: "#{T}/confirm", password: :valid,
      code: :bad, expect: :rails, status: 422 },
    { name: 'otp_confirm_password_first', method: :post, path: "#{T}/confirm", password: :wrong,
      otp: :provisioned, code: :current, expect: :rails, status: 401, error: 'password_required' },
    { name: 'otp_backup', method: :post, path: "#{T}/backup_codes", password: :valid,
      otp: :enabled, expect: :rails, crypto: :backup },
    { name: 'otp_backup_not_enabled', method: :post, path: "#{T}/backup_codes", password: :valid,
      expect: :rails, crypto: :backup },
    { name: 'otp_backup_no_password', method: :post, path: "#{T}/backup_codes",
      otp: :enabled, code: :current, expect: :rails, status: 401 },
    { name: 'otp_destroy', method: :delete, path: T, password: :valid,
      otp: :enabled, code: :current, expect: :rails, disabled: true },
    { name: 'otp_destroy_backup', method: :delete, path: T, password: :valid,
      otp: :enabled, code: :backup, expect: :rails, disabled: true },
    { name: 'otp_destroy_password_only', method: :delete, path: T, password: :valid,
      otp: :enabled, expect: :rails, status: 401, error: 'otp_required' },
    { name: 'otp_destroy_code_only', method: :delete, path: T,
      otp: :enabled, code: :current, expect: :rails, status: 401, error: 'password_required' },
    { name: 'otp_destroy_bad_code', method: :delete, path: T, password: :valid,
      otp: :enabled, code: :bad, expect: :rails, status: 401, error: 'otp_required' },
    { name: 'replay_head', path: P, method: :head, expect: :rails },
    { name: 'replay_suffix', path: "#{P}.json", expect: :rails },
    { name: 'replay_format', path: "#{P}?format=xml", expect: :rails },
    { name: 'replay_cloud', path: P, env: { 'SELF_HOSTED' => 'false' }, expect: :rails },
    { name: 'replay_kill', path: P, env: { 'DAWARICH_RAILS_SLICES' => 'api_account' }, expect: :rails },
    { name: 'replay_query_shape', path: "#{P}?unused[]=x", expect: :rails }
  ].concat(%w[setup confirm backup_codes destroy].flat_map do |action|
    path = action == 'destroy' ? T : "#{T}/#{action}"
    method = action == 'destroy' ? :delete : :post
    [{ name: "otp_#{action}_unavailable", path:, method:, expect: :rails, available: false,
       status: 503, error: 'two_factor_not_available' },
     { name: "otp_#{action}_pending", path:, method:, expect: :rails, user: { status: 3 },
       status: 402, error: 'payment_required' }]
  end).freeze
end
